name: Huntress CVE-2026-25049 Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Huntress Scanner
        run: |
          python huntress_scanner.py workflows/
        env:
          # Optional: fail build if risks found
          FAIL_ON_RISKS: "true"

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: huntress-scan-results
          path: scan-results.json