// frontend/src/utils/excelExport.js
// Generate Excel takeoff sheets with pricing

import * as XLSX from 'xlsx';

/**
 * Generate a complete Excel takeoff workbook
 * @param {Object} takeoffData - The takeoff data from Claude
 * @param {Object} pricingData - User-entered pricing information
 * @param {Object} projectInfo - Project metadata
 * @returns {Blob} Excel file blob ready for download
 */
export function generateTakeoffExcel(takeoffData, pricingData, projectInfo) {
  const workbook = XLSX.utils.book_new();
  
  // Sheet 1: Summary
  const summaryData = [
    ['TAKEOFF SUMMARY'],
    [''],
    ['Project:', projectInfo.name || 'Untitled Project'],
    ['Date:', new Date().toLocaleDateString()],
    ['Trade:', takeoffData.summary.tradeType],
    ['Estimator:', projectInfo.estimator || ''],
    [''],
    ['Total Line Items:', takeoffData.summary.totalLineItems],
    ['Confidence Score:', `${takeoffData.summary.confidence}%`],
    [''],
    ['Generated by:', 'Turbo Takeoff - Sovereign Edition'],
    ['', 'Two Mile Solutions LLC']
  ];
  
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  
  // Set column widths
  summarySheet['!cols'] = [
    { wch: 20 },
    { wch: 40 }
  ];
  
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
  
  // Sheet 2: Detailed Takeoff
  const takeoffHeaders = [
    'Item #',
    'Description',
    'Quantity',
    'Unit',
    'Material',
    'Manufacturer',
    'Unit Price',
    'Extended Price',
    'Supplier',
    'Location',
    'Spec Reference',
    'Notes'
  ];
  
  const takeoffRows = takeoffData.items.map((item, index) => {
    const pricing = pricingData[item.material] || {};
    const quantity = item.quantity || 0;
    const unitPrice = pricing.unitPrice || 0;
    const extended = quantity * unitPrice;
    
    return [
      index + 1,
      item.description || '',
      quantity,
      item.unit || '',
      item.material || '',
      item.manufacturer || pricing.manufacturer || '',
      unitPrice > 0 ? `$${unitPrice.toFixed(2)}` : '',
      extended > 0 ? `$${extended.toFixed(2)}` : '',
      pricing.supplier || '',
      item.location || '',
      item.specification || '',
      item.notes || ''
    ];
  });
  
  // Calculate totals
  const totalMaterials = takeoffRows.reduce((sum, row) => {
    const extended = parseFloat(String(row[7]).replace(/[$,]/g, '')) || 0;
    return sum + extended;
  }, 0);
  
  // Add totals row
  takeoffRows.push(
    ['', '', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', 'SUBTOTAL:', '', `$${totalMaterials.toFixed(2)}`, '', '', '', ''],
    ['', '', '', '', '', 'LABOR:', '', `$${(totalMaterials * (projectInfo.laborMultiplier || 0.3)).toFixed(2)}`, '', '', '', ''],
    ['', '', '', '', '', 'OVERHEAD:', '', `$${(totalMaterials * (projectInfo.overheadRate || 0.15)).toFixed(2)}`, '', '', '', ''],
    ['', '', '', '', '', 'PROFIT:', '', `$${(totalMaterials * (projectInfo.profitMargin || 0.10)).toFixed(2)}`, '', '', '', ''],
    ['', '', '', '', '', 'TOTAL:', '', `$${(totalMaterials * (1 + (projectInfo.laborMultiplier || 0.3) + (projectInfo.overheadRate || 0.15) + (projectInfo.profitMargin || 0.10))).toFixed(2)}`, '', '', '', '']
  );
  
  const takeoffData2D = [takeoffHeaders, ...takeoffRows];
  const takeoffSheet = XLSX.utils.aoa_to_sheet(takeoffData2D);
  
  // Format currency columns
  const currencyFormat = '$#,##0.00';
  const range = XLSX.utils.decode_range(takeoffSheet['!ref']);
  
  for (let row = 1; row <= range.e.r; row++) {
    const unitPriceCell = XLSX.utils.encode_cell({ r: row, c: 6 });
    const extendedCell = XLSX.utils.encode_cell({ r: row, c: 7 });
    
    if (takeoffSheet[unitPriceCell]) {
      takeoffSheet[unitPriceCell].z = currencyFormat;
    }
    if (takeoffSheet[extendedCell]) {
      takeoffSheet[extendedCell].z = currencyFormat;
    }
  }
  
  // Set column widths
  takeoffSheet['!cols'] = [
    { wch: 8 },  // Item #
    { wch: 35 }, // Description
    { wch: 10 }, // Quantity
    { wch: 6 },  // Unit
    { wch: 25 }, // Material
    { wch: 20 }, // Manufacturer
    { wch: 12 }, // Unit Price
    { wch: 14 }, // Extended
    { wch: 20 }, // Supplier
    { wch: 15 }, // Location
    { wch: 15 }, // Spec
    { wch: 30 }  // Notes
  ];
  
  XLSX.utils.book_append_sheet(workbook, takeoffSheet, 'Takeoff');
  
  // Sheet 3: Supplier Ethics
  if (pricingData.suppliers && pricingData.suppliers.length > 0) {
    const ethicsHeaders = [
      'Supplier',
      'Resonance Score',
      'Priority',
      'Indigenous Owned',
      'Veteran Owned',
      'IACA Certified',
      'BBB Rating',
      'OSHA Violations (3yr)',
      'Times Used',
      'Your Rating'
    ];
    
    const ethicsRows = pricingData.suppliers.map(supplier => [
      supplier.name,
      supplier.resonanceScore || 'N/A',
      supplier.priority || '',
      supplier.indigenousOwned ? 'Yes' : 'No',
      supplier.veteranOwned ? 'Yes' : 'No',
      supplier.iacaCertified ? 'Yes' : 'No',
      supplier.bbbRating || 'NR',
      supplier.oshaViolations || 0,
      supplier.timesUsed || 0,
      supplier.personalRating || 'Not Rated'
    ]);
    
    const ethicsData2D = [ethicsHeaders, ...ethicsRows];
    const ethicsSheet = XLSX.utils.aoa_to_sheet(ethicsData2D);
    
    ethicsSheet['!cols'] = [
      { wch: 25 }, // Supplier
      { wch: 12 }, // Score
      { wch: 8 },  // Priority
      { wch: 14 }, // Indigenous
      { wch: 12 }, // Veteran
      { wch: 12 }, // IACA
      { wch: 10 }, // BBB
      { wch: 16 }, // OSHA
      { wch: 10 }, // Times Used
      { wch: 12 }  // Rating
    ];
    
    XLSX.utils.book_append_sheet(workbook, ethicsSheet, 'Supplier Ethics');
  }
  
  // Sheet 4: Warnings & Notes
  if (takeoffData.warnings && takeoffData.warnings.length > 0) {
    const warningsData = [
      ['WARNINGS & NOTES'],
      [''],
      ['The following items require your attention:'],
      [''],
      ...takeoffData.warnings.map((warning, idx) => [`${idx + 1}. ${warning}`])
    ];
    
    const warningsSheet = XLSX.utils.aoa_to_sheet(warningsData);
    warningsSheet['!cols'] = [{ wch: 80 }];
    
    XLSX.utils.book_append_sheet(workbook, warningsSheet, 'Warnings');
  }
  
  // Generate Excel file
  const excelBuffer = XLSX.write(workbook, { 
    bookType: 'xlsx', 
    type: 'array',
    cellStyles: true
  });
  
  const blob = new Blob([excelBuffer], { 
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
  });
  
  return blob;
}

/**
 * Download the Excel file
 */
export function downloadTakeoffExcel(takeoffData, pricingData, projectInfo) {
  const blob = generateTakeoffExcel(takeoffData, pricingData, projectInfo);
  
  const fileName = `Takeoff_${projectInfo.name || 'Untitled'}_${new Date().toISOString().split('T')[0]}.xlsx`;
  
  // Create download link
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

/**
 * Export to Google Sheets (returns shareable link)
 */
export async function exportToGoogleSheets(takeoffData, pricingData, projectInfo) {
  // This would integrate with Google Sheets API
  // For MVP, we'll just download Excel and user can upload manually
  // Full implementation requires OAuth and Google Sheets API
  
  console.log('Google Sheets export - manual upload required for MVP');
  downloadTakeoffExcel(takeoffData, pricingData, projectInfo);
  
  return {
    success: true,
    message: 'Excel file downloaded. Upload to Google Sheets to share.'
  };
}